#!/usr/bin/python

import os
import sys

sys.path.append('../../../foamTools/python')
import pyOpenFOAM


# Read number of processors from command line (1 by default)
np = pyOpenFOAM.read_inputs(sys.argv)
print "Running with %d processors" % np

# Make the *.foam file for ParaView
pyOpenFOAM.touch_foam_files('test')

os.system('cp -r 0.org 0')

# Generate the initial mesh
print "Generating blockMesh"
pyOpenFOAM.run('blockMesh')

for i in range(0,3):
    print "Pre-Refinement loop", i
    pyOpenFOAM.run('VOFSetFields')
    pyOpenFOAM.run('initDynamicMesh')
    lasttime = pyOpenFOAM.get_sorted_time_folders(False).pop()
    os.system('rm '+lasttime+'/alpha1*')
    os.system('cp 0.org/* '+lasttime+'/')

pyOpenFOAM.run('VOFSetFields')



if np > 1:
    # For parallel runs, decompose the problem
    print "Decomposing problem"
    pyOpenFOAM.set_decompose_par(np,"simple",1) #aspect ratio = 1 H/W
    pyOpenFOAM.run('decomposePar',args='-cellDist')


# Run the problem
if np > 1:
    # Redistribute the mesh - NOT CURRENTLY WORKING
    #  this needs ptscotch while decomposePar needs scotch
    #print "Redistributing the mesh"
    #pyOpenFOAM.set_decompose_par(np,"ptscotch")
    #pyOpenFOAM.run('redistributePar',np,'-overwrite')

    # Renumber mesh
    #print "Renumbering the mesh"
    #pyOpenFOAM.run('renumberMesh',np,'-overwrite')

    # Begin parallel run
    print "Running the problem"
    pyOpenFOAM.run('interDyMFoam',np,hide=False)

    # Reconstruct the decomposed solution
    #for time_folder in pyOpenFOAM.get_sorted_time_folders():
    #    print "Reconstructing parallel mesh for time %s" % time_folder
    #    pyOpenFOAM.run('reconstructParMesh',args='-time '+time_folder)

    #    print "Reconstructing solution for time %s" % time_folder
    #    pyOpenFOAM.run('reconstructPar',args='-time '+time_folder)

else:
    print "Running the problem"
    pyOpenFOAM.run('interDyMFoam',hide=False)




print "Finished!"


