#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso ../../utilities/geometryTools
wmake libso ../../utilities/PLICInterface
wmake libso hsTwophaseMixtureThermo
wmake

# ----------------------------------------------------------------- end-of-file
