#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

cp -r 0.org 0
blockMesh
makeSphere
#interFoam
#interFoamPLIC


# ----------------------------------------------------------------- end-of-file
