#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

\rm -rf *~
\rm -rf 0 chemFoam.out log* output.log tmpFile
\rm -rf constant/chem.inp
\rm -rf constant/reactions
\rm -rf constant/thermo

# ----------------------------------------------------------------- end-of-file

